# Generated by Django 5.0.2 on 2024-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
